theimpossibleastronaut/rmw

src/functions/restore_rmw.c
I was planning to do more work on this before the next release, but decided to release early due to issue #21
=> merging restore() cleanup prior to release

src/main.c
Undo file is only opened if there has actually been a delete.
=> Fix Issue #29

src/main.c
=> Dev3 change

src/functions/purging_rmw.c, src/functions/purging_rmw.h, src/main.c
=> is_time_to_purge: remove HOMEDIR as an argument #60

src/functions/restore_rmw.c
=> undo_file issue (Update restore_rmw.c)

man/rmw-de.man
A german translation of the manpage.
=> Add German Man Page

man/rmw-es.man
=> Spanish man page

man/rmw-pt.man
=> added portuguese man

AUTHORS.md
I forgot to add myself to the AUTHORS file
=> Updated AUTHORS.md

man/rmw-pl.man
This changeset adds a Polish manpage, fixing issue #76.
=> Add Polish manpage

man/Makefile.am, man/Makefile.in, man/nl/rmw.1
Adds nl/rmw.1 for Dutch translation.
=> Dutch manpage translation per issue #109

po/nl_NL.po
Contains updates for the Dutch locale. Should be all up to date.
=> Update po file for Dutch

po/fi.po
=> added finnish translation

po/nl_NL.po
Adds missing translations and changed strings
=> Update NL translation

AUTHORS.md, po/rmw.pot
Translated all EN strings into pt-PT. Let me know if there are any issues!
=> Create Portuguese translation #120

AUTHORS.md, po/ru.po
Translated all the EN strings to Russian.
=> created Russian translation #144

po/pl_PL.po
This changeset corrects the declination of words inside plural forms for the Polish translation.
=> Improve handling of plural forms in the Polish translation

src/purging_rmw.c
Changes message to reflect desired output discussed in issue #137
=> [fixes #137] new messages for purging

.travis.yml
I think it may be failing because I changed the branch from the original
example provided by coverity
=> .travis.yml:use separate branch for coverity scan

.travis.yml, test/COMMON, test/Makefile.am, test/Makefile.in, test/README, test/basic.sh, test/purging.sh
=> improve tests

man/pt_BR/rmw.1
This pull request fixes issue #193.
=> Removed -B option from portuguese man page translation.

man/pl/rmw.1
-B Option was removed from pl man page.
=> #195 Removed -B option from pl man page

man/nl/rmw.1
=> Remove -B option in Dutch manpage

AUTHORS.md, README.md, src/Makefile.in, src/purging_rmw.c, src/purging_rmw.h, src/rmw.c, src/rmw.h, src/trivial_rmw.c, src/utils_rmw.c, src/utils_rmw.h, test/Makefile.in, test/purging.sh.in
=> Added an empty trash option.

po/nl_NL.po
Updated the Dutch strings for issue #250
=> Updated nl_NL translation for issue #250

po/nl_NL.po
Forgot to branch it, but it's up to date.
Greetings from the easter bunny.
=> Update PO files for NL

docs/_includes/head.html, docs/assets/overrides.css, docs/faq.md, po/nl_NL.po
Fix a small grammar on FAQ.
Add some breathing space by increasing margins.
Add a bit of font-size to body texts to increase readability.
Increase lineheight for readability.
Make the menu a fixed size so it flows better.
Also icons arent all of the same width, so realigned the menu properly to match that.
=> Site improvements

packaging/rmw-rpm.spec
=> add RPM spec template

.github/workflows/c-cpp.yml, ChangeLog, meson.build, meson_options.txt, po/meson.build, src/bst.c, src/bst.h, src/main.c, src/meson.build, src/restore_rmw.c
See https://github.com/vmactions/freebsd-vm for more info
=> c-cpp.yml:add test for FreeBSD

.github/workflows/c-cpp.yml
Minor changes noted in the README at
https://github.com/vmactions/freebsd-vm
=> .github/workflows/c-cpp.yml:update freebsd test

README.md, docker/README.md
=> README.md:add first draft of docker docs

.github/workflows/c-cpp.yml, .github/workflows/codeql.yml
(partially reverts 58fde3c0e3ed66d7c8e723bafb92d04d5df66846)
=> ci: split codeql into separate file

src/bsdutils/rm.c, src/purging_rmw.c, src/purging_rmw.h, src/utils_rmw.c, src/utils_rmw.h, test/test_purging.sh
https://github.com/theimpossibleastronaut/rmw/security/code-scanning/13
=> fix potential TOCTOU race condition

.github/workflows/cirrus-email.yml
https://cirrus-ci.org/guide/notifications/
=> cirrus-email.yml: notify on failures

.github/workflows/c-cpp.yml, src/bsdutils/meson.build
=> ci: add openbsd and include required headers for fts check

.github/workflows/c-cpp.yml
https://github.com/vmactions/openbsd-vm/issues/13#issuecomment-1830865067
#410
=> migrate openbsd-vm to v1

.github/workflows/c-cpp.yml
=> CI: Specify nofallback for brew canfigger test

ChangeLog, src/bsdutils/compat.h, src/messages_rmw.c, src/utils_rmw.c
I used https://github.com/crate-ci/typos to spot the error
=> Fix some typos spotted in the code and ChangeLog

ChangeLog, po/LINGUAS, po/fr.po
=> nls: Add French translation

.cirrus.yml, .github/workflows/macos.yml, meson.build
This partially reverts
https://github.com/theimpossibleastronaut/rmw/pull/457
=> meson: Add pkg_config_path to default_options
