theimpossibleastronaut/rmw

etc/rmw-en.man
This changeset adds an initial version of the manpage. The text is mostly copy-pasted from the README file.
If you care about i10n, I can also prepare a Polish version.
=> Add initial version of manpage

src/functions/config_rmw.c, src/main.c
The tool was not compiling on my mac. It seems the references to `ushort` are unsupported by the default make gcc compiler. 
I renamed those references to `unsigned short` and it compiles now.
=> Changed all ushort's to unsigned short

Makefile.am, Makefile.in, man/rmw.man
This should fix issue #81 . It does not handle different locales, not sure if that is possible with automake alone. There doesn't seem to be any support in automake for installing man pages with different locales.
I copied the english man file into ./man/rmw.man since automake doesn't support renaming the file as it gets copied. If the file name is rmw-en.man, it will be put into the man directory as rmw-en.1 and accessed with `man rmw-en`. 
Not sure if Makefile.in is generated when you run `./configure`, but it was a tracked file so I figured it should be added.
=> Issue81 fix

src/functions/strings_rmw.c
This changeset makes a warning be printed if one of the buffer-length checks in `escape_url()` or `unescape_url()` fails. Should fix issue #69.
=> Add warnings for buffer check fails

src/functions/restore_rmw.c
This changeset makes the list of files during `--select` display the file sizes along the file names. This should resolve issue #68.
=> Display file size during --select

.travis.yml
Adds osx platform. Builds with both gcc and clang. Sets language to c to validate the travis file and get a sane env.
=> Travis platforms

src/rmw.c
check the size of the parameter before the string is copied to the buffer
=> [fixes #156]

test/purging.sh
This adds a test for using RMWTRASH=empty
That feature is documented in README.md
This test is to help @GoldmanCPSciences with #137
=> purging.sh: add test for RMWTRASH=empty

src/rmw.c, test/purging.sh.in
Rmw would give this message if '-f' were used by itself, or '-v' and maybe in other cases too.
=> rmw.c:change message when insufficient options are given [skip ci]

src/config_rmw.c, src/config_rmw.h, src/purging_rmw.c, src/rmw.c, src/rmw.h
Make the code more uniform by moving user option flags into the cli_user_options struct. (@andy5995 's suggestion)
=> move other user option switches to cli_user_options.

src/config_rmw.c, src/messages_rmw.c, src/messages_rmw.h, src/purging_rmw.c, src/restore_rmw.c, src/rmw.c, src/rmw.h, src/trashinfo_rmw.c, src/utils_rmw.c
Addressed some coverity warnings, one of which was checking for the return value of lstat()
`make check` still passes all tests, but I noticed this in basic.sh.log
```
---
+ echo rmw should append a time_string to duplicate files...
rmw should append a time_string to duplicate files...
+ cd /home/andy/src/rmw-project/_build/test/tmp-home/tmp-files
+ touch 1
+ touch 2
+ touch 3
+ /home/andy/src/rmw-project/_build/src/rmw -c /home/andy/src/rmw-project/_build/../rmw/test/rmw.testrc 1 2 3
lstat: No such file or directory
lstat: Invalid argument
lstat: Invalid argument
3 files were removed to the waste folder
+ touch 1
+ touch 2
+ touch 3
+ /home/andy/src/rmw-project/_build/src/rmw -c /home/andy/src/rmw-project/_build/../rmw/test/rmw.testrc 1 2 3
lstat: No such file or directory
lstat: Invalid …
```
=> fix some coverity warnings

CONTRIBUTING.md
Fixed typo in the word 'typos'. Made me chuckle!
=> Fixed typo in contributing guidelines

src/parse_cli_options.c
Also adds -R dummy option to ensure compatibility with rm, and adds the
the option to the help output
=> change message when -r, --recursive is used

ChangeLog, README.md, man/rmw.1, meson.build, packaging/release-checklist.txt, src/main.c, src/messages_rmw.c, src/purging_rmw.c, src/purging_rmw.h, src/utils_rmw.c, test/meson.build, test/test_purging.sh
Co-authored-by: Andy5995 <arch_stanton5995@protonmail.com>
~WIP: valgrind tests still need to pass~
=> Use rm instead instead of custom function for purging

.github/workflows/docker-build-env.yml, .github/workflows/docker-meson.yml, .github/workflows/docker.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> docker workflows:migrate actions (use node16)

.github/workflows/c-cpp.yml, ChangeLog, docker/Dockerfile, src/bsdutils/meson.build
=> bsdutils/meson.build: find musl-fts on systems that require it

.github/workflows/c-cpp.yml
The concurrency change is unrelated.
=> CI: Workaround actions/runner-images#9491

ChangeLog, src/purging_rmw.c, src/time_rmw.c, test/meson.build
=> tests: Fix failing after year 2038

po/de.po, po/es_MX.po, po/fr.po, po/hi.po, po/nl.po, po/pl.po, po/pt_BR.po, po/rmw.pot, po/ru.po, po/uk.po, src/parse_cli_options.c
=> Remove handling of '-i'

src/messages_rmw.c, src/restore_rmw.c, src/restore_rmw.h, src/strings_rmw.c, src/strings_rmw.h
And improve the tests a little bit
The snprintf man page states under CAVEATS:
The glibc implementation of the functions snprintf() and vsnprintf() conforms to the C99 standard, that is,  behaves
as described above, since glibc 2.1.  Until glibc 2.0.6, they would return -1 when the output was truncated.
=> Use strcpy instead of snprintf (fix #464)

src/config_rmw.c, src/config_rmw.h, src/restore.c, src/trashinfo.h, src/utils.c, src/utils.h
=> Remove recently added support for symlinks
